provider:
  name: openfaas

functions:
  patreon-responder:
    lang: python
    handler: ./patreon-responder
    image: alexellis2/patreon-responder:0.4.0

    environment:
      write_debug: true
      read_debug: true
      display_removed: false
    secrets:
      - backer-thankyou-secrets
